Resolved Task #6
wladengine/m-01-threading pull request #6
Opened 2023-05-01 15:39 UTC by wladengine

2023-05-03 07:00 UTC, ASemykinBrl requested changes
Some inaccuracies should be fixed

2023-05-03 07:00 UTC, ASemykinBrl commented on MultiThreading.Task6.Continuation/Program.cs
> +        const TaskContinuationOptions regardlessOptions =
It's redindant in case of ordinal continuation

2023-05-08 15:15 UTC, wladengine commented on MultiThreading.Task6.Continuation/Program.cs
> +        const TaskContinuationOptions regardlessOptions =
Removed

2023-05-11 08:11 UTC, ASemykinBrl approved these changes

2023-05-11 12:04 UTC, merged